apiVersion: v1
kind: Secret
metadata:
  namespace: mongodb
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= # username
  mongo-root-password: cGFzc3dvcmQ= # password
