---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
      type: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        type: frontend
    spec:
      containers:
        - name: mycontainer
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
