---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 5
  template:
    metadata:
      name: webapp-pod
    spec:
      containers:
        - name: webapp
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: 'webapp-configmap'
          resources:
            requests:
              memory: '16Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
