---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  labels:
    app: mywebapp
    type: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: flask
  selector:
    app: mywebapp
    type: frontend
