apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configmap.name }}-{{ .Values.namespace }}"
  namespace: {{ .Values.namespace }}
data:
  BG_COLOR: {{ .Values.configmap.data.BG_COLOR | quote }}
  FONT_COLOR: {{ .Values.configmap.data.FONT_COLOR | quote }}
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER | quote }}