---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deploy
  labels:
    app: {{ .Values.appName }}
    type: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      type: frontend
  template:
    metadata:
      name: {{ .Values.appName }}-pod
      labels:
        app: {{ .Values.appName }}
        type: frontend
      namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: mycontainer
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          resources:
            requests:
              memory: '16Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'