---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  labels:
    app: mywebapp
    type: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: flask
  selector:
    app: mywebapp
    type: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deploy
  labels:
    app: mywebapp
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
      type: frontend
  template:
    metadata:
      name: mywebapp-pod
      labels:
        app: mywebapp
        type: frontend
    spec:
      containers:
        - name: mycontainer
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
